### ISSUE TITLE
Cannot Download all files

### ISSUE THREAD

**Issue by edremy-Ohagi** [hoangcaominh/RealTimeDRCPointsDisplayer#6]
I can't download the rubic file and the world record file.Their exit codes are all 1.What can I do to download files successfully and use this calculator?
This is such a good program for our small race and I really want to be able to use it.Thanks a lot!

**Comment by Yuyutato** [comment]
This is Broken For Me Aswell. Its a Problem Affecting Most People I Belive

**Comment by Rika-TH** [comment]
Cao has pushed an update that should fix this now

**Comment by hoangcaominh** [comment]
The url to download data was outdated, so I fixed it in the 2..0.1 update.
You should be able to update via the dialog upon opening it.

**Comment by edremy-Ohagi** [comment]
I tested it this morning and it works well now,thx for fixing!
