### ISSUE TITLE
Cannot Read TH18 UM

### ISSUE THREAD

**Issue by edremy-Ohagi** [hoangcaominh/RealTimeDRCPointsDisplayer#9]
Live DRC Points Calculator needs to be updated now, as UM has come out a while but the calculator cannot read it. Thx for the update!

**Comment by hoangcaominh** [comment]
Live DRC Points Calculator is outdated now and THLSC is its replacement. It supports UM but doesn't have score tracker and DRC points calculator. You can find it [here](https://github.com/hoangcaominh/THLSC).
Sorry for the inconvenience!

**Comment by edremy-Ohagi** [comment]
No problem, thanks for your reply and your calculators/couters!
